feat(task): Реализация сервиса управления контрагентами.
ChiniakinD/contractor pull request #1
Opened 2024-07-08 10:11 UTC by ChiniakinD

Реализация RESTful веб-сервиса для управления данными о контрагентах, странах, отраслях и формах организаций.

2024-07-08 14:48 UTC, gobaz095 reviewed
И тесты хочу не только на слой контроллеров, но также хотя бы на слой репозиториев. Сервисы тоже нужны обычно. В данном случае, у тебя это все пересекается и отличается мало. Но чаще всего логика репозитори и сервиса отличается сильно, и контроллер тоже может иметь свою логику. Плюс мы тестируем немного разные вещи, DTO != entity. А на бы надо проверить что у нас именно интеграционные тесты с БД работают как надо. И сохраняется и возвращается одно и тоже из БД.

И на экспепшены тоже хочу тесты, раз они написаны.

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/config/JdbcConfig.java
> +    public DataSource dataSource() {
А почему зачем тогда конфиги в application.yaml?

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/config/mapper/ContractorMapper.java
> +        ContractorModel contractorModel = modelMapper.map(contractor, ContractorModel.class);
Ок, но надо быть очень аккуратным с автоматическими мапперами. Иногда даже стоит написать отдельно тесты.

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/controller/ContractorController.java
> +    @GetMapping("/search")
Для исключения путаницы лучше назвать /all

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        if (contractorFilter.getOgrn() != null) {
Зависит от бизнес логики, но может не помешать isBlank

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        sqlQuery.append("where 1=1");
Можно и тупо собрать where и если оно пустое не добавлять. Но и так и так пойдет.

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        List<Object> params = new ArrayList<>();
Чтобы уменьшить риск дальнейших ошибок при изменении этого метода, лучше использовать именованные переменные Map<String, Object> params или вообще MapSqlParameterSource

2024-07-08 14:48 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +            List<Contractor> contractors = jdbcTemplate.query(sqlQuery.toString(), params.toArray(), (rs, rowNum) -> {
вынести (rs, rowNum) -> в отдельный маппер бы

2024-07-08 14:54 UTC, gobaz095 requested changes
И не вижу интеграционных тестов с testcontainers.
И в задании был все же liquibase, а не flyway. Это более мощный и гибкий инструмент на данный момент.

2024-07-08 23:54 UTC, ChiniakinD commented on src/main/java/com/chiniakin/config/JdbcConfig.java
> +    public DataSource dataSource() {
[528a890](https://github.com/ChiniakinD/contractor/pull/1/commits/528a89085d158072d793a7a341a9c0d3585ff505)

2024-07-08 23:54 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        if (contractorFilter.getOgrn() != null) {
https://github.com/ChiniakinD/contractor/pull/1/commits/6b77a090a3424f5115004cd0e8cbc5a030511f54

2024-07-08 23:55 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +            List<Contractor> contractors = jdbcTemplate.query(sqlQuery.toString(), params.toArray(), (rs, rowNum) -> {
https://github.com/ChiniakinD/contractor/pull/1/commits/8ce7289cde05c2af0d9ee12e33d3ef4d444c3f6e

2024-07-08 23:55 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        List<Object> params = new ArrayList<>();
https://github.com/ChiniakinD/contractor/pull/1/commits/27cfb03da5649a6ad2747c3b1117a298cb3cbf51

2024-07-09 10:19 UTC, gobaz095 requested changes

2024-07-09 10:19 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +            sqlQuery.append(" and name = name");
Ошибка забыл : 
тестами покрой)

2024-07-09 10:19 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +            sqlQuery.append(" and name_full = nameFull");
Ошибка забыл : 
тестами покрой)

2024-07-09 10:21 UTC, gobaz095 requested changes

2024-07-09 10:21 UTC, gobaz095 commented on src/main/resources/liquibase/migration/V2__insert.sql
Добавь пожалуйста к миграциям описание. например как тут, с автором и тд:
https://habr.com/ru/articles/251617/

2024-07-09 15:04 UTC, ChiniakinD commented on src/main/resources/liquibase/migration/V2__insert.sql
https://github.com/ChiniakinD/contractor/pull/1/commits/019430e589ab02c78c01854b063ef16f13e5f429

2024-07-09 15:42 UTC, gobaz095 approved these changes
Можно влить, описание swagger и прочее отдельным уже ПРом.

2024-07-09 15:42 UTC, gobaz095 commented on src/main/java/com/chiniakin/config/mapper/ContractorRowMapper.java
> +        Contractor contractor = new Contractor()
Верю что ты усвоил паттерн билдер:) Можешь использовать ломбоковский. @Builder

2024-07-09 15:42 UTC, gobaz095 commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        contractorRepository.save(contractor);
Не критично, но если мы говорим о производительности, то зачем нам тянуть целиком объект чтобы у него изменить одно поле? Легче сразу сделать update contractor set is_active = false where id = id

2024-07-09 15:42 UTC, gobaz095 commented on src/main/resources/liquibase/migration/V1__init_schema.sql
В будущем попробуй yaml, он предпочтительнее из-за систематизации изменений, единообразия, большей выходной информации и тд.

2024-07-09 15:42 UTC, gobaz095 commented on src/main/java/com/chiniakin/model/ContractorModel.java
Про описание сваггера, на всякий случай, я ожидаю увидеть тут @Schema, и все прочее в контроллерах.

2024-07-09 21:56 UTC, gobaz095 approved these changes
ок

2024-07-10 07:27 UTC, ChiniakinD commented on src/main/java/com/chiniakin/config/mapper/ContractorRowMapper.java
> +        Contractor contractor = new Contractor()
https://github.com/ChiniakinD/contractor/pull/1/commits/b6341ff18612cce9edabdb63ed74a780cf9dadb1

2024-07-10 12:10 UTC, ChiniakinD commented on src/main/java/com/chiniakin/service/ContractorServiceImpl.java
> +        contractorRepository.save(contractor);
https://github.com/ChiniakinD/contractor/pull/1/commits/d2708c2cac73e30ce5c2d1e8d67def19e0cc255c

2024-07-10 18:07 UTC, merged